Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

E:\Vijay\Django\Demo>virtualenv venv
created virtual environment CPython3.10.11.final.0-64 in 6932ms
  creator CPython3Windows(dest=E:\Vijay\Django\Demo\venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\nimaiuser\AppData\Local\pypa\virtualenv)
    added seed packages: pip==24.3.1, setuptools==75.6.0, wheel==0.45.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

E:\Vijay\Django\Demo>venv\Scripts\activate

(venv) E:\Vijay\Django\Demo>django-admin startproject myproject

(venv) E:\Vijay\Django\Demo>django-admin startproject Apps

(venv) E:\Vijay\Django\Demo>django-admin startproject Apps .

(venv) E:\Vijay\Django\Demo>pip install django
Collecting django
  Downloading Django-5.1.4-py3-none-any.whl.metadata (4.2 kB)
Collecting asgiref<4,>=3.8.1 (from django)
  Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting sqlparse>=0.3.1 (from django)
  Downloading sqlparse-0.5.3-py3-none-any.whl.metadata (3.9 kB)
Collecting tzdata (from django)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting typing-extensions>=4 (from asgiref<4,>=3.8.1->django)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Downloading Django-5.1.4-py3-none-any.whl (8.3 MB)
   ---------------------------------------- 8.3/8.3 MB 5.4 MB/s eta 0:00:00
Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)
Downloading sqlparse-0.5.3-py3-none-any.whl (44 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Installing collected packages: tzdata, typing-extensions, sqlparse, asgiref, django
Successfully installed asgiref-3.8.1 django-5.1.4 sqlparse-0.5.3 typing-extensions-4.12.2 tzdata-2024.2

(venv) E:\Vijay\Django\Demo>python manage.py

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[contenttypes]
    remove_stale_contenttypes

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    optimizemigration
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver

(venv) E:\Vijay\Django\Demo>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
December 20, 2024 - 12:57:26
Django version 5.1.4, using settings 'Apps.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[20/Dec/2024 12:57:37] "GET / HTTP/1.1" 200 12068
Not Found: /favicon.ico
[20/Dec/2024 12:57:38] "GET /favicon.ico HTTP/1.1" 404 2206

(venv) E:\Vijay\Django\Demo>pip install psycopg2
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002322E5B7F40>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/psycopg2/
ERROR: Operation cancelled by user

(venv) E:\Vijay\Django\Demo>python manage.py makemigrations
No changes detected

(venv) E:\Vijay\Django\Demo>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK

(venv) E:\Vijay\Django\Demo>python manage.py makemigrations
Traceback (most recent call last):
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\db\backends\postgresql\base.py", line 25, in <module>
    import psycopg as Database
ModuleNotFoundError: No module named 'psycopg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\db\backends\postgresql\base.py", line 27, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Vijay\Django\Demo\manage.py", line 22, in <module>
    main()
  File "E:\Vijay\Django\Demo\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "D:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\contrib\auth\models.py", line 5, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\contrib\auth\base_user.py", line 40, in <module>
    class AbstractBaseUser(models.Model):
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\db\models\base.py", line 143, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\db\models\base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\db\models\options.py", line 231, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\utils\connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\utils\connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\db\utils.py", line 193, in create_connection
    backend = load_backend(db["ENGINE"])
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\db\utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
  File "D:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\Vijay\Django\Demo\venv\lib\site-packages\django\db\backends\postgresql\base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module

(venv) E:\Vijay\Django\Demo>pip install psycopg2
Collecting psycopg2
  Downloading psycopg2-2.9.10-cp310-cp310-win_amd64.whl.metadata (5.0 kB)
Downloading psycopg2-2.9.10-cp310-cp310-win_amd64.whl (1.2 MB)
   ---------------------------------------- 1.2/1.2 MB 2.7 MB/s eta 0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.10

(venv) E:\Vijay\Django\Demo>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK

(venv) E:\Vijay\Django\Demo>python manage.py startapp Index

(venv) E:\Vijay\Django\Demo>python manage.py createsuperuser
Username (leave blank to use 'nimaiuser'): Demoadmin
Email address: admin@gmail.com
Password:
Password (again):
Superuser created successfully.

(venv) E:\Vijay\Django\Demo>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
December 20, 2024 - 13:28:51
Django version 5.1.4, using settings 'Apps.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Not Found: /
[20/Dec/2024 13:28:59] "GET / HTTP/1.1" 404 2304
[20/Dec/2024 13:29:04] "GET /Index HTTP/1.1" 301 0
[20/Dec/2024 13:29:04] "GET /Index/ HTTP/1.1" 200 9
[20/Dec/2024 13:29:11] "GET /admin HTTP/1.1" 301 0
[20/Dec/2024 13:29:11] "GET /admin/ HTTP/1.1" 302 0
[20/Dec/2024 13:29:14] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4160
[20/Dec/2024 13:29:14] "GET /static/admin/css/login.css HTTP/1.1" 200 951
[20/Dec/2024 13:29:15] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
[20/Dec/2024 13:29:15] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
[20/Dec/2024 13:29:15] "GET /static/admin/css/base.css HTTP/1.1" 200 22092
[20/Dec/2024 13:29:15] "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
[20/Dec/2024 13:29:15] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
[20/Dec/2024 13:29:15] "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
[20/Dec/2024 13:29:24] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[20/Dec/2024 13:29:24] "GET /admin/ HTTP/1.1" 200 5856
[20/Dec/2024 13:29:24] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
[20/Dec/2024 13:29:24] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[20/Dec/2024 13:29:24] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
E:\Vijay\Django\Demo\Index\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
December 20, 2024 - 13:34:42
Django version 5.1.4, using settings 'Apps.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

